site_name: Curso aTemporal
site_url: https://devgustavinho.github.io/curso-atemporal
docs_dir: docs
repo_url: https://github.com/devgustavinho/curso_atemporal
repo_name: devgustavinho/curso-atemporal
edit_uri: tree/main/docs

theme:
  name: material
  custom_dir: overrides
  logo: assets/svg/logo2.svg
  favicon: assets/svg/logo.svg
  language: pt
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - search.suggest
    - search.highlight
    - search.share
  palette:
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/weather-sunny
        name: Modo claro
    - scheme: default
      primary: indigo
      toggle:
        icon: material/weather-night
        name: Modo noturno

markdown_extensions:
  - pymdownx.critic
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.keys
  - footnotes
  - admonition
  - markdown.extensions.attr_list
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html

fonts:
  icon: material/format-font
  preferences:
    - text: Default
    - text: Roboto
      code: Roboto Mono
    - text: OpenDyslexic
      code: OpenDyslexicMono
      src: https://fonts.cdnfonts.com/css/opendyslexic

extra_javascript:
  - https://unpkg.com/mermaid@10.9.1/dist/mermaid.min.js

extra:
  social:
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@nice_gustavinho
    - icon: fontawesome/brands/github
      link: https://github.com/devgustavinho
    - icon: fontawesome/brands/twitch
      link: https://www.twitch.tv/nice_gustavinho